name: yuro_generator
description: Yuro annotation generator.
version: 0.4.0
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.0.3
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  analyzer: ^2.7.0

  yuro_annotation:
    path: ../yuro_annotation
