name: yuro_generator
description: Yuro annotation generator.
version: 0.1.1
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.1.0
  source_gen: ^1.0.3
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  analyzer: ^2.7.0

  yuro_annotation: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0