name: yuro_generator
description: Yuro annotation generator.
version: 0.2.1
homepage: https://github.com/YuroLtd/yuro_generator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.1.0
  source_gen: ^1.2.5
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  analyzer: ^4.7.0

  yuro_annotation: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0