name: yuro_generator
description: Yuro annotation generator.
version: 0.0.1
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
#  yuro: ^0.2.0
  meta: ^1.3.0
  source_gen: ^1.0.1
  code_builder: ^4.0.0
  dart_style: ^2.0.1

# NOTE: remove before publishing
#dependency_overrides:
  yuro:
    path: ../yuro


