name: yuro_generator
description: Yuro annotation generator.
version: 0.0.1
homepage: https://github.com/YuroLtd/yuro_kit.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yuro: ^0.2.0

# NOTE: remove before publishing
dependency_overrides:
  yuro:
    path: ../yuro

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
